# Form implementation generated from reading ui file 'HomeWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(parent=Home)
        self.pushButton.setGeometry(QtCore.QRect(50, 60, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "Form"))
        self.pushButton.setText(_translate("Home", "PushButton"))
