# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(677, 535)
        MainWindow.setStyleSheet("#menu_widget {\n"
"    \n"
"    background-color: rgb(243, 243, 243);\n"
"}\n"
"\n"
"#main_widget {\n"
"    border-top-left-radius: 20px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QWidget#MainWindow {\n"
"    background-color: rgb(243, 243, 243); /* 设置标题栏背景颜色 */\n"
"    color: white; /* 设置标题栏文字颜色 */\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(MainWindow)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu_widget = QtWidgets.QWidget(parent=MainWindow)
        self.menu_widget.setMinimumSize(QtCore.QSize(80, 0))
        self.menu_widget.setMaximumSize(QtCore.QSize(64, 16777215))
        self.menu_widget.setStyleSheet("QPushButton {\n"
"            background-color: transparent;\n"
"            border: 2px solid transparent; /* 初始时透明边框 */\n"
"            border-radius: 15px; /* 圆角 */\n"
"            padding: 10px 20px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            border-color: #555; /* 鼠标悬停时边框颜色 */\n"
"        }\n"
"        QPushButton:pressed {\n"
"            border-color: #555; /* 鼠标点击时边框颜色 */\n"
"        }")
        self.menu_widget.setObjectName("menu_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menu_widget)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 504, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.menu_widget)
        self.main_widget = QtWidgets.QStackedWidget(parent=MainWindow)
        self.main_widget.setObjectName("main_widget")
        self.horizontalLayout.addWidget(self.main_widget)

        self.retranslateUi(MainWindow)
        self.main_widget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "时雪"))
