# Form implementation generated from reading ui file 'RunWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Run(object):
    def setupUi(self, Run):
        Run.setObjectName("Run")
        Run.resize(783, 621)
        Run.setStyleSheet("#Run {\n"
"            border-top-left-radius: 20px;\n"
"}\n"
"#Widget {\n"
"            border-top-left-radius: 20px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Run)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=Run)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(parent=self.tab)
        self.textEdit.setStyleSheet("background-color: rgb(24, 24, 24);\n"
"font: 11pt \"微软雅黑\";\n"
"color: rgb(85, 218, 85);")
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 2, 1)
        self.widget_5 = QtWidgets.QWidget(parent=Run)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PersonaTableWidget = QtWidgets.QTableWidget(parent=self.widget_5)
        self.PersonaTableWidget.setMinimumSize(QtCore.QSize(0, 256))
        self.PersonaTableWidget.setLineWidth(0)
        self.PersonaTableWidget.setObjectName("PersonaTableWidget")
        self.PersonaTableWidget.setColumnCount(0)
        self.PersonaTableWidget.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.PersonaTableWidget)
        self.gridLayout.addWidget(self.widget_5, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(parent=Run)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.StopButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.StopButton.setMinimumSize(QtCore.QSize(0, 30))
        self.StopButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.StopButton.setObjectName("StopButton")
        self.gridLayout_2.addWidget(self.StopButton, 0, 0, 1, 1)
        self.StopAllButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.StopAllButton.setMinimumSize(QtCore.QSize(0, 30))
        self.StopAllButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.StopAllButton.setObjectName("StopAllButton")
        self.gridLayout_2.addWidget(self.StopAllButton, 0, 1, 1, 1)
        self.ResumeButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.ResumeButton.setMinimumSize(QtCore.QSize(0, 30))
        self.ResumeButton.setObjectName("ResumeButton")
        self.gridLayout_2.addWidget(self.ResumeButton, 1, 0, 1, 1)
        self.ResumeAllButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.ResumeAllButton.setMinimumSize(QtCore.QSize(0, 30))
        self.ResumeAllButton.setObjectName("ResumeAllButton")
        self.gridLayout_2.addWidget(self.ResumeAllButton, 1, 1, 1, 1)
        self.UnbindButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.UnbindButton.setMinimumSize(QtCore.QSize(0, 30))
        self.UnbindButton.setObjectName("UnbindButton")
        self.gridLayout_2.addWidget(self.UnbindButton, 2, 0, 1, 1)
        self.UnbindAllButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.UnbindAllButton.setMinimumSize(QtCore.QSize(0, 30))
        self.UnbindAllButton.setObjectName("UnbindAllButton")
        self.gridLayout_2.addWidget(self.UnbindAllButton, 2, 1, 1, 1)
        self.StartButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.StartButton.setMinimumSize(QtCore.QSize(0, 30))
        self.StartButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.StartButton.setObjectName("StartButton")
        self.gridLayout_2.addWidget(self.StartButton, 3, 0, 1, 2)
        self.gridLayout.addWidget(self.widget_2, 1, 0, 1, 1)

        self.retranslateUi(Run)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Run)

    def retranslateUi(self, Run):
        _translate = QtCore.QCoreApplication.translate
        Run.setWindowTitle(_translate("Run", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Run", "日志"))
        self.StopButton.setText(_translate("Run", "暂停"))
        self.StopAllButton.setText(_translate("Run", "全部暂停"))
        self.ResumeButton.setText(_translate("Run", "恢复"))
        self.ResumeAllButton.setText(_translate("Run", "全部恢复"))
        self.UnbindButton.setText(_translate("Run", "解绑"))
        self.UnbindAllButton.setText(_translate("Run", "全部解绑"))
        self.StartButton.setText(_translate("Run", "开始"))
